---
downloads: ~/.ansible-downloads/

configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - FaceTime
  - iTunes
  - iBooks
  - Calendar
dockitems_persist: 
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 2
  - name: Alacritty 
    path: /Applications/Alacritty.app
    pos: 3
  - name: Music
    path: /Applications/Music.app
    pos: 4
  - name: Discord
    path: /Applications/Discord.app
    pos: 5
  - name: System Preferences
    path: "/Applications/System Preferences.app" 
    pos: 6

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - awscli
  - fzf
  - gettext
  - git
  - node
  - neovim
  - nvm
  - openssl
  - postgresql
  - pyenv
  - readline
  - ssh-copy-id
  - sketchybar
  - skhd
  - stow
  - sqlite
  - tmux
  - tree-sitter
  - yabai
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-verisons
  - homebrew/services
  - koekeishiya/formulae
  - mongodb/brew
  - heroku/brew
  - felixkratz/formulae

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - brave-browser
  - discord
  - docker
  - font-jetbrains-mono
  - google-chrome
  - google-drive
  - iterm2
  - omnidisksweeper
  - pgadmin4
  - postman
  - private-internet-access
  - robo-3t
  - vagrant

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages: 
  - name: emmet-ls
    state: present # present/absent/latest, default: present
    version: "^0.2.2" # default: N/A
  - name: pyright
    state: present
    version: "^1.1.225"
  - name: typescript-language-server
    state: present
    version: "^0.9.7"
  - name: typescript
    state: present
    version: "^4.6.2"
  - name: vscode-langservers-extracted
    state: present
    version: "^4.1.0"
  - name: yarn
    state: latest
  - name: nodemon
    state: latest
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
