version: '3'

vars:
  DOTFILES_REPO: "git@github.com:PaulJequann/dotfiles.git"
  DOTFILES_DIR: "{{.HOME}}/.dotfiles"

includes:
  common: .taskfiles/common.yml
  macos:
    taskfile: .taskfiles/macos.yml
    platforms: [darwin]
  linux:
    taskfile: .taskfiles/linux.yml
    platforms: [linux]
  wsl:
    taskfile: .taskfiles/wsl.yml
    platforms: [linux]
  arch:
    taskfile: .taskfiles/arch.yml
    platforms: [linux]

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  detect:
    desc: Detect current platform and environment
    silent: true
    cmds:
      - |
        echo "Platform: {{OS}}/{{ARCH}}"
        if [ -f /proc/version ] && grep -qi microsoft /proc/version; then
          echo "Environment: WSL2"
        elif [ "{{OS}}" = "darwin" ]; then
          echo "Environment: macOS"
        elif [ -f /etc/arch-release ]; then
          echo "Environment: Arch Linux"
        else
          echo "Environment: Linux"
        fi
        if command -v brew &> /dev/null; then
          echo "Homebrew: installed"
        else
          echo "Homebrew: not installed (run ./bootstrap.sh)"
        fi

  setup:
    desc: Full system setup for current platform
    cmds:
      - task: detect
      - |
        {{if eq OS "darwin"}}
        task macos:setup
        {{else if eq OS "linux"}}
        if [ -f /proc/version ] && grep -qi microsoft /proc/version; then
          task wsl:setup
        elif [ -f /etc/arch-release ]; then
          task arch:setup
        else
          task linux:setup
        fi
        {{end}}
      - task: common:setup

  packages:
    desc: Install all packages via Homebrew
    cmds:
      - task: common:packages

  dotfiles:
    desc: Setup dotfiles
    cmds:
      - task: common:dotfiles

  ssh:
    desc: Generate SSH key for this device
    cmds:
      - task: common:ssh

  terminal:
    desc: Setup terminal (zsh, tmux, etc)
    cmds:
      - task: common:terminal

  sync:
    desc: Sync device_configs and dotfiles, install new packages
    cmds:
      - task: common:sync

  gui:
    desc: Install GUI applications
    cmds:
      - |
        {{if eq OS "darwin"}}
        task common:gui
        {{else if eq OS "linux"}}
        if [ -f /etc/arch-release ]; then
          task arch:gui
        else
          task common:gui
        fi
        {{end}}

  update:
    desc: Update all packages via Homebrew
    cmds:
      - |
        {{if eq OS "darwin"}}
        task macos:update
        {{else if eq OS "linux"}}
        if [ -f /etc/arch-release ]; then
          task arch:update
        else
          task linux:update
        fi
        {{end}}

  clean:
    desc: Clean up caches and temporary files
    cmds:
      - |
        {{if eq OS "darwin"}}
        task macos:clean
        {{else if eq OS "linux"}}
        if [ -f /etc/arch-release ]; then
          task arch:clean
        else
          task linux:clean
        fi
        {{end}}

  check:
    desc: Check system configuration and installed tools
    cmds:
      - task: common:check
